# mysql-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  # O valor aqui é "root123" codificado em base64
  # Você pode gerar o seu com: echo -n "SUA_SENHA_AQUI" | base64
  MYSQL_ROOT_PASSWORD: cm9vdDEyMw==